### ISSUE TITLE
Не правильно переводит обратно

### ISSUE THREAD

**Issue by alexeygritsenko** [alekseynemiro/Nemiro.Convertion#1]
Добрый день, прежде всего моя благодарность за столь полезную библиотеку!
Однако, столкнулся с проблемой, при переводе обратно только что полученного значения системой счисления оно отличается от первоначального((((
Тестовый код:

```
        string DIC = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        long res1 = Convertion.FromBaseX("ABC", DIC);
        string res2 = Convertion.ToBaseX(res1, DIC);

        if ("ABC" != res2) 
            Console.WriteLine("Не верно перевел обратно!");
```

**Comment by alekseynemiro** [comment]
С указанным набором символов:
**A** - это ноль
**B** - 1
**C** - 2
**D** - 3 
...
**K** - 10
...
**U** - 20
...
**Z** - 25
**BA** - 26
**BB** - 27
и т.п.

**AA** - ноль
**AB** - один, так же как и **B**
**ABC** - 028, т.е. число 28, также как и **BC**

Поскольку метод **FromBaseX** возвращает число, то первый ноль убирается.

Поэтому **ABC** не равно **BC**, т.е. **028** не равно **28**. 

Чтобы сравнить строку **028** с числом **28**, её нужно преобразовать в число:

``` C#
if (Convert.ToInt64("028") == 28)
{
  Console.WriteLine("028 = 28");
}
```

Аналогичным образом следует поступать и с числами собственной системы исчисления:

``` C#
if (Convertion.FromBaseX("ABC", DIC) == Convertion.FromBaseX("BC", DIC))
{
  Console.WriteLine("ABC = BC");
}
```

Но числа **ABC** по идее быть не должно, так же как и **028**. Не получится получить такие числа при математических операциях.

**Comment by alexeygritsenko** [comment]
Спасибо за ответ, теперь я понял почему это происходит. В мат. операциях может нет, но в моей задаче это крайне важно. Не могли бы Вы опционально добавить такую возможность, исключающую отброс нулей, с включением примерно так:

```
var res11 = Convertion.FromBaseX("ABC", DIC, true);
var res22 = Convertion.ToBaseX(res11, DIC, true);
```

**Comment by alekseynemiro** [comment]
Проще всего убирать нули, при помощи метода **TrimStart**:

``` C#
string DIC = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
string num = "ABC";
var res11 = Convertion.FromBaseX(num.TrimStart('A'), DIC);
var res22 = Convertion.ToBaseX(res11, DIC);
Console.WriteLine("{0} = {1}", res11, res22);
```

[Посмотреть, как это работает](https://dotnetfiddle.net/aDZjBA).

Или можно переделать функцию **FromBaseX**, чтобы она возвращала строку, вместо числа:

``` C#
public static string FromBaseX(string value, string charset)
{
  if (String.IsNullOrEmpty(charset)) { throw new ArgumentNullException("charset"); }
  long result = 0;
  int basis = charset.Length;
  bool negative = value.StartsWith("-");
  if (negative) { value = value.Substring(1); }
    string zeros = "";
    for (int i = value.Length - 1; i >= 0; i -= 1)
    {
        long n = Convert.ToInt64(charset.IndexOf(value[i]) * (Math.Pow(basis, (value.Length - i - 1))));
        if (n == 0)
        {
            zeros += "0";
        }
        else
        {
            zeros = "";
        }
        result += n;
    }

    string resultStr = zeros;
    if (negative) { resultStr = "-" + resultStr; }
    resultStr += result.ToString();

    return resultStr;
}
```

[Посмотреть работу примера](https://dotnetfiddle.net/oVRVW2).

Либо внедрить туда отсекание нулей через **TrimStart**.

Я бы выбрал вариант с **TrimStart**, он проще всего. Внедрять пока не буду, не вижу смысла, т.к. это вопрос форматирования строк, а не работы с числами. Еще обдумаю эту тему, но скорых действий в этом направлении с моей стороны ожидать не стоит.

**Comment by alexeygritsenko** [comment]
Спасибо, но если уж делать такое то нужна поддержка с обеих сторон) ABC это 028 то и 028 это ABC) кстати побывал в начало алфавита добавить любой левый знак, тогда перевод работал в обе стороны, но значение отличалось от оригинального, поэтому отказался от него. В итоге решил проблему другим бубном, но теперь вроде ништяк)
